// 鱼定村小馆 · 设定数据（移植自 qucuo 烹饪系统 + 川菜味型图鉴 + NPC 口味表）
// 纯数据，不碰 DOM / 存档。

export const QUAL_BONUS = { 白: 0, 绿: 5, 蓝: 10, 紫: 15 };

// ── 技法（5 种）· unlock=0 表示初始掌握 ────────────────────────────────
export const TECHNIQUES = {
  炖: { id: "炖", icon: "🍲", needsSteamer: false, unlock: 0,
    desc: "文火慢煨，什么都能炖。不挑调料，新手保底。" },
  炒: { id: "炒", icon: "🥘", needsSteamer: false, unlock: 0, buffAttr: "身法",
    desc: "旺火快炒，锅气足，出餐快。" },
  煎: { id: "煎", icon: "🍳", needsSteamer: false, unlock: 0,
    desc: "少油慢煎，两面金黄，豆腐鱼排都靠它。" },
  炸: { id: "炸", icon: "🫧", needsSteamer: false, unlock: 0, buffAttr: "体魄",
    desc: "宽油旺火，外酥里嫩，酥肉洋芋都离不开。" },
  烤: { id: "烤", icon: "🔥", needsSteamer: false, unlock: 12, buffAttr: "体魄",
    desc: "明火炙烤，肉食加成，焦香入骨。" },
  腌: { id: "腌", icon: "🫙", needsSteamer: false, unlock: 10,
    desc: "盐醋封坛，日久味长，冷吃开胃。" },
  蒸: { id: "蒸", icon: "♨", needsSteamer: true, unlock: 18,
    desc: "竹笼水汽，原味不夺。效果最强，需蒸笼。" },
  卤: { id: "卤", icon: "🍯", needsSteamer: false, unlock: 14,
    desc: "老卤慢浸，五香入骨，一锅老汤养十年。" },
  凉拌: { id: "凉拌", icon: "🥢", needsSteamer: false, unlock: 8,
    desc: "不点火，红油一拌就成，夏天最开胃。" },
};
export const TECHNIQUE_IDS = Object.keys(TECHNIQUES);

// ── 炊具（10 件）· 溪边旧铁锅灶房自带 ──────────────────────────────────
export const COOKWARE = [
  { id: "jiutieguo", name: "溪边旧铁锅", quality: "白", default: true, canSteam: false, price: 0,
    desc: "锅沿磕了三个豁口，鱼定大娘说补补还能用十年。灶房自带，炖炒皆可。" },
  { id: "taoguan", name: "熊山陶炖罐", quality: "白", canSteam: false, price: 8,
    desc: "熊山红陶，炖汤不夺味，摔不烂。" },
  { id: "caitan", name: "黑风寨腌菜坛", quality: "白", canSteam: false, price: 8,
    desc: "坛沿水封得严实，腌三年不坏。" },
  { id: "chaoguo", name: "孟记熟铁炒锅", quality: "绿", canSteam: false, price: 16,
    desc: "孟铁匠锻的，锅气足，炒什么都香。" },
  { id: "zhenglong", name: "竹编蒸笼（三层）", quality: "绿", canSteam: true, price: 9,
    desc: "雅江冷箭竹编的，蒸出来带竹香。唯一能上蒸的炊具。" },
  { id: "kaojia", name: "跑马会炭烤架", quality: "绿", canSteam: false, price: 12,
    desc: "铁条焊的，烤全羊都架得住。" },
  { id: "tonghu", name: "铜吊壶", quality: "绿", canSteam: false, price: 10,
    desc: "煮茶煮汤两相宜，铜绿养出来了。" },
  { id: "shizaofu", name: "雪山派石灶釜", quality: "蓝", canSteam: true, price: 30,
    desc: "雪山顶寒铁铸的，导热极匀，亦可蒸。" },
  { id: "falan", name: "锦官城珐琅砂锅", quality: "蓝", canSteam: false, price: 24,
    desc: "官窑珐琅彩，柳青鸢办公桌上炖汤用的同款。" },
  { id: "qingtongding", name: "三星堆仿青铜鼎", quality: "紫", canSteam: true, price: 60,
    desc: "鸭子河畔淘沙人挖出来的，仿商周制式，炖肉有金石气。" },
];
export const COOKWARE_BY_ID = Object.fromEntries(COOKWARE.map(c => [c.id, c]));
export const DEFAULT_COOKWARE_ID = "jiutieguo";

// ── 六大味型 · requires=核心调料（必须在料槽里才算调出此味）────────────
export const FLAVORS = [
  { id: "xianxiang", name: "鲜香", label: "清鲜本味，盐提鲜、酱生香", unlock: 0,
    requires: ["贡措海盐"], desc: "咸鲜为主，宁淡勿咸。盐、酱、孜然皆在此味。" },
  { id: "qingdan", name: "清淡", label: "姜葱爽口，原味不夺", unlock: 0,
    requires: ["鱼定村野葱油"], desc: "葱油清香，吃的是食材自己的味道。" },
  { id: "mala", name: "麻辣", label: "麻香打颤，辣而不燥", unlock: 12,
    requires: ["熊山花椒"], desc: "花椒当家，舌尖打颤才够格。" },
  { id: "suanla", name: "酸辣", label: "醇酸微辣，开胃爽口", unlock: 10,
    requires: ["黑风寨苞谷醋"], desc: "苞谷醋的酸，配一点辣，酸得正。" },
  { id: "tian", name: "甜", label: "纯甜而香，回甘绵长", unlock: 10,
    requires: ["雪山野蜂蜜"], desc: "野蜂蜜入膳，甜得干净。" },
  { id: "tiansuan", name: "甜酸", label: "甜酸味厚，似荔枝酸甜", unlock: 16,
    requires: ["黑风寨苞谷醋", "雪山野蜂蜜"], desc: "糖醋路子，先酸后甜，席面收尾的味。" },
];
export const FLAVOR_BY_ID = Object.fromEntries(FLAVORS.map(f => [f.id, f]));

// ── 食材 / 调味品 · flavor 仅调味品有（它贡献的味型）──────────────────
export const INGREDIENTS = [
  { name: "熊山花椒", kind: "调味品", flavor: "mala", price: 3,
    lore: "麻得舌尖打颤，冷锅鱼底料的灵魂，产自曲措乡熊山。" },
  { name: "贡措海盐", kind: "调味品", flavor: "xianxiang", price: 1,
    lore: "咸而微甘，贡措海畔石上自结的霜，不是晒的，是湖水自己结的。" },
  { name: "锦官豆瓣酱", kind: "调味品", flavor: "xianxiang", price: 2,
    lore: "咸鲜微辣回甜，晒足一年方出缸，锦官城菜的底子。" },
  { name: "雅江菜籽油", kind: "调味品", flavor: "qingdan", price: 1,
    lore: "青香微辛，冷榨而成，青衣楼冷锅鱼就用这个油。" },
  { name: "雪山野蜂蜜", kind: "调味品", flavor: "tian", price: 4,
    lore: "甜带松脂气，量极少，何雨谢一年只收两罐。" },
  { name: "大草甸孜然", kind: "调味品", flavor: "xianxiang", price: 2,
    lore: "辛香暖人，马帮从西域带回，跑马会烤肉必备。" },
  { name: "黑风寨苞谷醋", kind: "调味品", flavor: "suanla", price: 2,
    lore: "酸得粗粝，苞谷酒糟二次发酵，巴桑说酸得正。" },
  { name: "喇嘛庙藏红花", kind: "调味品", flavor: "xianxiang", price: 6,
    lore: "微苦暖香，能染色，入药入膳两用，佛前的东西不浪费。" },
  { name: "天都镇酱油", kind: "调味品", flavor: "xianxiang", price: 2,
    lore: "咸鲜焦香，黄豆晒制，孟铁匠打铁间隙翻缸。" },
  { name: "鱼定村野葱油", kind: "调味品", flavor: "qingdan", price: 2,
    lore: "辛甜葱香浓，鱼定大娘春天熬的，一罐用半年。" },
  { name: "熊山松茸", kind: "食材", price: 2,
    lore: "菌香浓，不可水洗，洗了就没了山的味道，要用小刀刮泥松针擦。" },
  { name: "青城山蕨菜", kind: "食材", price: 1,
    lore: "嫩滑微涩，青城后山所产，松鹤道长说练完剑吃这个清火。" },
  { name: "熊山铁棍山药", kind: "食材", price: 1,
    lore: "粉糯黏液多，熊山北坡沙土里挖，一杆下去三尺深。" },
  { name: "雪山雪莲瓣", kind: "食材", price: 8,
    lore: "清苦回甘冰凉，雪山顶峰雪莲心里采，何雨谢一年只许采三瓣。" },
  { name: "贡措海苔花", kind: "食材", price: 2,
    lore: "鲜而微腥，贡措海浅滩石上刮的，丹增说那是湖底长上来的头发。" },
  { name: "大草甸野韭", kind: "食材", price: 1,
    lore: "辛香冲鼻，比家韭冲三倍，春天头茬最嫩。" },
  { name: "狼曲冷水鱼", kind: "食材", price: 2,
    lore: "肉细刺多鲜甜，狼曲上游石缝里，雪团拍水震鱼嘎则拿草绳串。" },
  { name: "青衣江团鱼", kind: "食材", price: 3,
    lore: "肉厚无刺胶质重，冷锅鱼的正主，青衣楼一天用二十条。" },
  { name: "贡措海裂腹鱼", kind: "食材", price: 4,
    lore: "肉紧微咸自带盐味，贡措海深处，一年只吃一次是丹增的规矩。" },
  { name: "熊曲石斑", kind: "食材", price: 2,
    lore: "肉嫩带苔香，熊曲急流石下，老孙钓的，一年只有两个月肥。" },
  { name: "牦牛腱子肉", kind: "食材", price: 2,
    lore: "纤维粗肉味浓，玉泉寨牧民散养，炖三时辰才烂，急不得。" },
  { name: "藏香猪五花", kind: "食材", price: 3,
    lore: "脂香带松果味，雪山派后山散养，吃松果野菌长大，烤起来满山香。" },
  { name: "大草甸黄羊腿", kind: "食材", price: 4,
    lore: "肉紧膻味轻，跑马大会烤全羊用的就是这个。" },
  { name: "雪山雪鸡肉", kind: "食材", price: 3,
    lore: "肉紧而嫩清炖最佳，加一味当归就够，加多了尝不出雪鸡自己的味。" },
  { name: "牦牛奶酪", kind: "食材", price: 2,
    lore: "奶香带一丝青草味，卓玛用自家牦牛奶做的鲜酪，春天吃野花的牛，奶做的酪是甜的。" },
  { name: "熊猫笋", kind: "食材", price: 1,
    lore: "嫩清甜带竹香，熊猫啃剩的冷箭竹笋尖，护谷弟子说别捡但确实好吃。" },
  { name: "鱼定村青稞", kind: "食材", price: 1,
    lore: "粗嚼劲足微甜，糌和青稞饼的原料。" },
  { name: "玉泉寨土豆", kind: "食材", price: 1,
    lore: "粉沙煮烂即化，不挑地，石头缝也长。" },
  { name: "雅江嫩豆腐", kind: "食材", price: 1,
    lore: "嫩豆香易碎，青衣江的水点的卤，别处做不出。" },
  { name: "大草甸蘑菇", kind: "食材", price: 1,
    lore: "鲜肉厚伞大，雨后草坡上的白伞，不能生吃。" },
  { name: "锦官城干笋", kind: "食材", price: 2,
    lore: "脆吸味耐煮，雅江鲜笋晒干运来，泡发要一夜。" },
  // ── 川滇新增（20 味）──────────────────────────────────────────────
  { name: "二荆条辣椒", kind: "调味品", flavor: "mala", price: 2,
    lore: "川西二荆条，辣得香不辣得燥，回口还带一点甜。" },
  { name: "汉源清溪花椒", kind: "调味品", flavor: "mala", price: 4,
    lore: "贡椒，唐代就进贡的那种，麻得正，不苦不涩。" },
  { name: "泡海椒", kind: "调味品", flavor: "suanla", price: 2,
    lore: "老坛泡足一年的海椒，鱼香味的魂，剁碎了油一激就出香。" },
  { name: "保宁醋", kind: "调味品", flavor: "suanla", price: 3,
    lore: "阆中麸醋，酸得柔和回甜，跟苞谷醋两路子，这个温柔。" },
  { name: "潼川豆豉", kind: "调味品", flavor: "xianxiang", price: 2,
    lore: "豆豉乌黑发亮，豉香浓，回锅肉离了它就不对。" },
  { name: "叙府芽菜", kind: "调味品", flavor: "xianxiang", price: 2,
    lore: "宜宾芽菜，咸甜脆嫩，燃面、咸烧白都靠它吊味。" },
  { name: "玫瑰花酱", kind: "调味品", flavor: "tian", price: 4,
    lore: "昆明安宁玫瑰舂的酱，甜里带花香，蘸乳扇是一绝。" },
  { name: "酸木瓜", kind: "调味品", flavor: "suanla", price: 2,
    lore: "滇西酸木瓜，煮鱼酸汤的酸是果酸，不是醋酸，清香。" },
  { name: "香茅草", kind: "调味品", flavor: "qingdan", price: 2,
    lore: "傣家香茅，手一拍就出柠檬香，烤鱼包肉都用它。" },
  { name: "单山蘸水", kind: "调味品", flavor: "mala", price: 2,
    lore: "昆明单山蘸水，辣椒面配了十几种香料，蘸什么都香。" },
  { name: "宣威火腿", kind: "食材", price: 4,
    lore: "滇腿，切开是玫瑰色，咸香吊汤第一，切片空口吃也行。" },
  { name: "见手青", kind: "食材", price: 3,
    lore: "牛肝菌，手一摸就青，必须炒透——炒不透就见小人。" },
  { name: "鸡枞菌", kind: "食材", price: 4,
    lore: "蚁巢上长的，鲜得掉眉毛，撕丝炸油鸡枞能香一罐。" },
  { name: "干巴菌", kind: "食材", price: 5,
    lore: "其貌不扬一身褶子，异香，云南人拿它当宝贝。" },
  { name: "大理乳扇", kind: "食材", price: 3,
    lore: "牛奶拉成扇，烤到鼓泡蘸玫瑰糖，白族人的甜。" },
  { name: "石屏豆腐", kind: "食材", price: 2,
    lore: "井水点的豆腐，烤到鼓泡包浆，外焦里嫩。" },
  { name: "饵块", kind: "食材", price: 1,
    lore: "大米舷的，烧饵块抹上酱，昆明人的一天从它开始。" },
  { name: "过桥米线", kind: "食材", price: 1,
    lore: "米线细白，汤要滚，料自己往下烫，讲究个顺序。" },
  { name: "折耳根", kind: "食材", price: 1,
    lore: "鱼腥草，爱的人爱死，恨的人绕道，凉拌最凶。" },
  { name: "雕梅", kind: "食材", price: 3,
    lore: "大理雕梅，用刀雕出纹的梅子，酸甜开胃，炖肉解腻。" },
  // ── 小吃用料 ────────────────────────────────────────────────────
  { name: "绿豆", kind: "食材", price: 1,
    lore: "圆绿豆，煮汤起沙，夏天一锅绿豆汤最解暑。" },
  { name: "内江红糖", kind: "调味品", flavor: "tian", price: 2,
    lore: "内江红糖，甜得厚，凉糕冰粉少不了它。" },
  { name: "冰粉籽", kind: "食材", price: 2,
    lore: "冰粉籽手搓出浆，点成冰粉，颤巍巍一碗清凉。" },
  { name: "蜀南大米", kind: "食材", price: 1,
    lore: "蜀南大米，蒸饭粒粒分明，豆花饭的底。" },
  { name: "竹签", kind: "食材", price: 1,
    lore: "削尖的竹签，穿肉穿菜，烤串的家伙什。" },
];
export const ING_BY_NAME = Object.fromEntries(INGREDIENTS.map(i => [i.name, i]));

// 商店常规食材不带星；★高级食材由探秘时 AI 即兴生成，存 st.stars（运行时），与商店区别开
export const STAR_MAP = {};
export const starOf = (n) => STAR_MAP[n] || 0;
export const starLabel = (n) => starOf(n) ? "★".repeat(starOf(n)) : "";

// ── 食材分类标签：调料/肉/菜/主食/其他 ───────────────────────────────
export const ING_TAGS = ["调料", "肉", "菜", "主食", "其他"];
const _TAG = {
  调料: ["熊山花椒","贡措海盐","锦官豆瓣酱","雅江菜籽油","雪山野蜂蜜","大草甸孜然","黑风寨苞谷醋","喇嘛庙藏红花","天都镇酱油","鱼定村野葱油","二荆条辣椒","汉源清溪花椒","泡海椒","保宁醋","潼川豆豉","叙府芽菜","玫瑰花酱","酸木瓜","香茅草","单山蘸水","内江红糖"],
  肉: ["牦牛腱子肉","藏香猪五花","大草甸黄羊腿","雪山雪鸡肉","狼曲冷水鱼","青衣江团鱼","贡措海裂腹鱼","熊曲石斑","宣威火腿"],
  菜: ["熊山松茸","青城山蕨菜","熊山铁棍山药","贡措海苔花","大草甸野韭","熊猫笋","玉泉寨土豆","雅江嫩豆腐","大草甸蘑菇","锦官城干笋","见手青","鸡枞菌","干巴菌","石屏豆腐","折耳根"],
  主食: ["鱼定村青稞","蜀南大米","过桥米线","饵块"],
};
export function ingTag(name) {
  for (const [t, arr] of Object.entries(_TAG)) if (arr.includes(name)) return t;
  return "其他";
}

// ── 小吃品类（苏唐的活计）· cat=汤/饭/点心/串/小吃 ────────────────────
export const SNACKS = [
  { id: "douhua", name: "豆花饭", cat: "饭" },
  { id: "langya", name: "狼牙土豆", cat: "小吃" },
  { id: "laonai", name: "老奶洋芋", cat: "小吃" },
  { id: "kaochuan", name: "烤串", cat: "串" },
  { id: "lüdou", name: "绿豆汤", cat: "汤" },
  { id: "bingfen", name: "红糖冰粉", cat: "点心" },
  { id: "danhong", name: "蛋烘糕", cat: "点心" },
];
export const SET_CATS = ["汤", "饭", "点心", "串", "小吃"];

// 商店常备（刷新也总在架）
export const SHOP_BASICS = ["贡措海盐", "雅江菜籽油", "熊山花椒", "二荆条辣椒",
  "玉泉寨土豆", "蜀南大米", "绿豆", "竹签"];

// ── 配方（10 道）· 料槽组合×技法，命中=固定菜名 ────────────────────────
export const RECIPES = [
  { name: "牦牛骨汤", technique: "炖", materials: ["牦牛腱子肉", "贡措海盐"],
    desc: "骨髓熬化了，汤白得像奶。卓玛说这汤是给病人喝的——不是药，但比药暖。" },
  { name: "松茸炖雪鸡", technique: "炖", materials: ["雪山雪鸡肉", "熊山松茸", "贡措海盐"],
    desc: "何雨谢亲手炖的，小火煨一天一夜。呼延雪说师母只炖过三次。" },
  { name: "烤藏香猪", technique: "烤", materials: ["藏香猪五花", "大草甸孜然"],
    desc: "吃松果野菌长大的，烤起来一股松脂香。呼延雪闻闻味道就当吃过了。" },
  { name: "烤黄羊腿", technique: "烤", materials: ["大草甸黄羊腿", "贡措海盐", "大草甸孜然"],
    desc: "跑马大会集市上现烤的，孜然辣椒撒得厚。梅朵每年跑完马都要吃半条。" },
  { name: "冷锅鱼", technique: "炒", materials: ["青衣江团鱼", "熊山花椒", "雅江菜籽油"],
    desc: "青衣楼招牌。冷锅底料铺七分熟鱼片，不开火先吃鱼。不吃冷锅鱼等于没来过雅江。" },
  { name: "熊猫笋炒腊肉", technique: "炒", materials: ["熊猫笋", "牦牛腱子肉", "熊山花椒"],
    desc: "熊猫啃剩的冷箭竹笋尖配腊肉，嫩得能掐出水。护谷弟子说别捡——但确实好吃。" },
  { name: "酸汤裂腹鱼", technique: "腌", materials: ["贡措海裂腹鱼", "黑风寨苞谷醋", "贡措海盐"],
    desc: "苞谷醋腌的裂腹鱼，酸得开胃。丹增说这鱼自带盐味，是贡措海的眼泪。" },
  { name: "腊牦牛肉", technique: "腌", materials: ["牦牛腱子肉", "贡措海盐", "熊山花椒"],
    desc: "盐与花椒封坛，风干半月。含在嘴里慢慢泡软，一块能吃一上午。" },
  { name: "雪莲蒸蛋", technique: "蒸", materials: ["雪山雪莲瓣", "牦牛奶酪", "贡措海盐"],
    desc: "雪莲瓣入蛋，竹笼水汽一蒸，清苦回甘。何雨谢一年只许采三瓣雪莲。" },
  { name: "松茸蒸鸡", technique: "蒸", materials: ["雪山雪鸡肉", "熊山松茸", "喇嘛庙藏红花"],
    desc: "藏红花染出金黄，松茸提鲜。住持说佛前的东西不能浪费，入膳也是修行。" },
  // ── 川滇新增配方 ─────────────────────────────────────────────────
  { name: "回锅肉", technique: "炒", materials: ["藏香猪五花", "潼川豆豉", "二荆条辣椒"],
    desc: "灯盏窝儿卷起来，豆豉二荆条下锅，肥而不腻，下饭三碗起步。" },
  { name: "鱼香肉丝", technique: "炒", materials: ["牦牛腱子肉", "泡海椒", "保宁醋"],
    desc: "没有鱼却有鱼香，泡海椒保宁醋糖醋一兑，咸甜酸辣兼备。" },
  { name: "见手青炒火腿", technique: "炒", materials: ["见手青", "宣威火腿"],
    desc: "菌子炒透、火腿煸香，滇人拿命换的一盘鲜，油要宽火要足。" },
  { name: "油鸡枞", technique: "炒", materials: ["鸡枞菌", "雅江菜籽油"],
    desc: "鸡枞撕丝慢火炸干，油封一罐，拌面夹馍能香一整个冬天。" },
  { name: "烤乳扇", technique: "烤", materials: ["大理乳扇", "玫瑰花酱"],
    desc: "乳扇架火上烤到鼓泡，抹一层玫瑰糖，卷起来吃，甜香拉丝。" },
  { name: "小锅米线", technique: "炖", materials: ["过桥米线", "宣威火腿", "酸木瓜"],
    desc: "小铜锅单锅煮，火腿吊味酸木瓜提酸，米线吸汤，滚烫上桌。" },
  { name: "烧饵块", technique: "烤", materials: ["饵块", "叙府芽菜"],
    desc: "饵块烤到微焦抹上芽菜酱，咸甜一口，昆明早点的魂。" },
  { name: "折耳根拌豆腐", technique: "腌", materials: ["折耳根", "雅江嫩豆腐", "单山蘸水"],
    desc: "折耳根掐节拌嫩豆腐，单山蘸水一撒，爱的人能吃一整盘。" },
  { name: "香煎石屏豆腐", technique: "煎", materials: ["石屏豆腐", "贡措海盐"],
    desc: "井水豆腐煎到鼓泡包浆，外焦里嫩，蘸水一碟就够。" },
  { name: "油酥肉", technique: "炸", materials: ["藏香猪五花", "鱼定村青稞"],
    desc: "青稞面裹五花宽油一炸，酥得掉渣，下酒一流。" },
];

// ── 客人 · 味型/技法/兴趣食材/消费力/点菜口吻（源自 NPC 口味表）────────
export const GUESTS = [
  { id: "caidan", name: "才旦", ident: "村长之女", spend: 20,
    flavor: "qingdan", tech: "炖", fav: "大草甸蘑菇",
    order: "嘴里常是薄荷凉——别太咸，清清淡淡炖一锅就好。" },
  { id: "laosun", name: "老孙", ident: "老孙饭馆掌柜", spend: 24,
    flavor: "xianxiang", tech: "炖", fav: "狼曲冷水鱼",
    order: "来碗鱼汤，要鲜。咸淡我一口就尝得出来。" },
  { id: "daniang", name: "鱼定大娘", ident: "村里厨娘", spend: 20,
    flavor: "tian", tech: "蒸", fav: "雪山野蜂蜜",
    order: "甜奶茶不离手——给大娘蒸个甜的吧。" },
  { id: "basang", name: "巴桑", ident: "黑风寨汉子", spend: 28,
    flavor: "mala", tech: "炒", fav: "熊山花椒",
    order: "无辣不欢，麻香打颤才够格，炒一盘来。" },
  { id: "danzeng", name: "丹增", ident: "贡措海渔人", spend: 28,
    flavor: "xianxiang", tech: "炖", fav: "贡措海裂腹鱼",
    order: "吃鱼只认海里的鲜，别夺了它自己的味。" },
  { id: "zhuoma", name: "卓玛", ident: "村里妇人", spend: 24,
    flavor: "xianxiang", tech: "炖", fav: "牦牛腱子肉",
    order: "认老火慢炖——肉要烂，汤要暖。" },
  { id: "huasao", name: "花嫂", ident: "村口摆摊", spend: 16,
    flavor: "qingdan", tech: "炒", fav: "玉泉寨土豆",
    order: "家常口，土豆下饭就知足，别放太多油盐。" },
  { id: "asuo", name: "阿索", ident: "小牧童", spend: 14,
    flavor: "tian", tech: "烤", fav: "牦牛奶酪",
    order: "奶酪蘸蜂蜜的吃法是我教的——烤过的更香。" },
  { id: "laoliehu", name: "老猎户", ident: "村口猎户", spend: 24,
    flavor: "xianxiang", tech: "烤", fav: "大草甸黄羊腿",
    order: "烤肉要撒厚孜然，山风里就该吃这个。" },
  { id: "zhaxi", name: "扎西", ident: "马帮商人", spend: 50,
    flavor: "xianxiang", tech: "烤", fav: "大草甸孜然",
    order: "马帮把孜然从西域带回——没孜然等于没出门。" },
  { id: "wenzhanggui", name: "温掌柜", ident: "锦官城商人", spend: 80,
    flavor: "xianxiang", tech: "炒", fav: "锦官豆瓣酱",
    order: "一口尝得出豆瓣晒了几年——酱香要浓，火要旺。" },
  { id: "huyanxue", name: "呼延雪", ident: "雪山派小师妹", spend: 60,
    flavor: "tian", tech: "蒸", fav: "雪山雪莲瓣",
    order: "松子糖不离身——甜是她的软肋。" },
  { id: "meiduo", name: "梅朵", ident: "土司之女", spend: 60,
    flavor: "mala", tech: "烤", fav: "大草甸黄羊腿",
    order: "跑马回来的姑娘——烤肉要撒厚辣椒。" },
  { id: "qingyilou", name: "青衣楼老板娘", ident: "雅江冷锅鱼掌柜", spend: 90,
    flavor: "mala", tech: "炒", fav: "青衣江团鱼",
    order: "麻味打颤才够格，鱼要嫩，油要正。" },
  { id: "caimai", name: "黑风寨采买的", ident: "寨里跑腿", spend: 34,
    flavor: "suanla", tech: "炒", fav: "黑风寨苞谷醋",
    order: "巴桑说酸得正——再来点辣，酸辣口才开胃。" },
  { id: "shusheng", name: "锦官城来的书生", ident: "赶考路上", spend: 44,
    flavor: "tiansuan", tech: "炒", fav: "雅江嫩豆腐",
    order: "糖醋里脊那路子——甜酸味厚，最好不过。" },
  // ── 川滇新增客人 ─────────────────────────────────────────────────
  { id: "maguotou", name: "滇西马锅头", ident: "赶马帮的", spend: 56,
    flavor: "xianxiang", tech: "炒", fav: "见手青",
    order: "菌子要炒透，火腿要厚——见手青我敢吃，炒一盘来。" },
  { id: "baiguniang", name: "大理白族姑娘", ident: "三道茶的", spend: 44,
    flavor: "tian", tech: "烤", fav: "大理乳扇",
    order: "乳扇烤到起泡，蘸玫瑰糖——甜的要，别烤糊。" },
  { id: "paochuan", name: "宜宾跑船的", ident: "川江号子", spend: 36,
    flavor: "xianxiang", tech: "炒", fav: "叙府芽菜",
    order: "芽菜下饭，咸甜口——炒一盘，再烫壶酒。" },
  { id: "daijiak", name: "傣家客人", ident: "版纳来的", spend: 40,
    flavor: "qingdan", tech: "烤", fav: "香茅草",
    order: "香茅草拍一拍，烤鱼包肉都行——要那股柠檬香。" },
  // ── 补全口味 + 苏酥 ────────────────────────────────────────────
  { id: "suniang", name: "酸娘子", ident: "醋坊老板娘", spend: 40,
    flavor: "suanla", tech: "炒", fav: "黑风寨苞谷醋",
    order: "酸要酸得亮堂，辣要辣得痛快——酸辣口才开胃。" },
  { id: "tangcu", name: "糖醋举子", ident: "赶考举子", spend: 46,
    flavor: "tiansuan", tech: "煎", fav: "雅江嫩豆腐",
    order: "糖醋适口，甜酸味厚些，煎得两面金黄最好。" },
  { id: "qingxu", name: "清虚道长", ident: "青城道士", spend: 36,
    flavor: "qingdan", tech: "炖", fav: "青城山蕨菜",
    order: "清淡养性，勿油腻——一锅素炖足矣。" },
  { id: "lasan", name: "辣三娘", ident: "江湖厨娘", spend: 52,
    flavor: "mala", tech: "炒", fav: "熊山花椒",
    order: "麻辣要够劲，麻得跳脚才好，别手软。" },
  { id: "xianbo", name: "鲜伯", ident: "退休老饕", spend: 60,
    flavor: "xianxiang", tech: "炖", fav: "青衣江团鱼",
    order: "要一个鲜字——吊汤见真章，别糊弄老头子。" },
  { id: "tiannan", name: "甜囡", ident: "糖铺小姐", spend: 38,
    flavor: "tian", tech: "蒸", fav: "雪山野蜂蜜",
    order: "甜要甜得干净，蒸的润一点。" },
  { id: "susu", name: "苏酥", ident: "苏唐的姐姐·御姐", spend: 120, sister: true,
    flavor: "xianxiang", tech: "蒸", fav: "雪山雪莲瓣",
    order: "妹妹的师兄？手艺如何——做道雅致的来，别让我等太久。" },
];

export const START_INV = {
  "贡措海盐": 3, "雅江菜籽油": 3, "鱼定村野葱油": 2, "熊山花椒": 2,
  "黑风寨苞谷醋": 1, "雪山野蜂蜜": 1, "牦牛腱子肉": 2, "狼曲冷水鱼": 2,
  "熊猫笋": 2, "大草甸蘑菇": 2, "玉泉寨土豆": 2, "熊山松茸": 1,
  // 川滇投放
  "二荆条辣椒": 2, "泡海椒": 1, "潼川豆豉": 1, "见手青": 1,
  "过桥米线": 2, "叙府芽菜": 1, "大理乳扇": 1,
};
export const START_COINS = 12;

export const HOURS = ["卯时·开门", "午时·客来", "未时·客来", "酉时·客来", "戌时·收功"];

// ── 探秘地图：十个据点，一据点对一类情境，点开地图选地方去 ──────────
// top/left 是相对底图（assets/map_bg.png）宽高的百分比坐标，不是视口。
export const EXPEDITION_MAP = [
  { id: "xuedong",   name: "雪线古洞", category: "探洞地宫", top: 32, left: 15 },
  { id: "yakou",     name: "风雪垭口", category: "天灾",     top: 15, left: 67 },
  { id: "linchang",  name: "转经林场", category: "密林采山", top: 58, left: 20 },
  { id: "yeyi",      name: "牧道野驿", category: "奇遇",     top: 74, left: 8 },
  { id: "gudao",     name: "黑风古道", category: "劫镖江湖", top: 62, left: 47 },
  { id: "koudu",     name: "官道渡口", category: "水域",     top: 79, left: 72 },
  { id: "zaoshi",    name: "早市坊",   category: "市井",     top: 83, left: 38 },
  { id: "miaohui",   name: "庙会集场", category: "节庆",     top: 10, left: 46 },
  { id: "chengjiao", name: "城郊人家", category: "人情",     top: 90, left: 87 },
  { id: "guancheng", name: "关城商市", category: "商贸",     top: 91, left: 46 },
];

// 探秘情境 100 种，按十类分好（轻度武侠，一据点一类，各据点各记各的上次，不重复）
export const EXP_SCEN_BY_CAT = {
  市井: ["市井讨价还价", "早市抢货", "夜市捡漏", "与胡商砍价", "当铺赎物",
    "粮行议价", "药铺赊账", "铁匠铺订刀", "布庄换料", "酒坊讨酒"],
  奇遇: ["奇遇·老丐传艺", "奇遇·落难客商", "奇遇·隐士指点", "奇遇·捡到头彩", "奇遇·山洪救人",
    "奇遇·古井秘藏", "奇遇·雷劈老树", "奇遇·白狐引路", "奇遇·游方郎中", "奇遇·说书人赠言"],
  劫镖江湖: ["劫镖·黑风截道", "护镖·夜走官道", "劫镖·马帮火并", "截胡·夺回赃物", "江湖·擂台赌菜",
    "江湖·厨会斗艺", "江湖·踢馆挑衅", "江湖·恩怨调解", "劫镖·镖银失窃", "江湖·夜探贼巢"],
  探洞地宫: ["探山洞·钟乳滴泉", "下地宫·石门锁阵", "探山洞·暗河渡险", "下地宫·长明灯阵", "探山洞·蝙蝠惊群",
    "下地宫·塌陷逃生", "探山洞·石髓采撷", "下地宫·古墓避毒", "探山洞·一线天光", "下地宫·水牢摸鱼"],
  密林采山: ["穿密林·瘴气迷途", "穿密林·兽径追踪", "采山·雨后捡菌", "采山·悬崖采药", "穿密林·藤蔓缠人",
    "采山·雪线寻莲", "穿密林·夜宿山神庙", "采山·溪边网鱼", "穿密林·蜂群夺蜜", "采山·秋风打枣"],
  水域: ["渡口摆渡", "湖心采菱", "急流放排", "冰面凿鱼", "滩涂赶海",
    "夜钓灯下", "瀑布取泉", "沼泽采藕", "退潮拾贝", "春汛捞鲜"],
  节庆: ["赶集·庙会采买", "端午采艾", "中秋打桂花", "重阳登高采菊", "腊八熬粥备料",
    "年关宰年猪", "春社分肉", "秋收打谷", "冬至包饺子", "上元猜灯谜"],
  人情: ["拜访·老厨讨教", "拜山·猎户分肉", "走亲戚·带土仪", "送菜·府衙宴", "接风·马帮洗尘",
    "谢师·送束脩", "探病·送药膳", "贺寿·做寿面", "满月·送红蛋", "吊唁·送素席"],
  天灾: ["山火抢收", "风雪封山抢路", "泥石流后寻人", "狼群围村护院", "夜半救火",
    "洪后捞物", "旱年寻水", "雹后抢收", "雾夜迷路", "沙暴避风"],
  商贸: ["行商·走村串户", "以物易物", "赊账收账", "拍卖·头彩竞价", "赶集·摆摊卖菜",
    "订购·包下果园", "预售·年菜订金", "换季·清仓甩卖", "团购·府衙采买", "尾货·收山货"],
};
